version: '3.9'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: images-uploader
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"